### PR TITLE
Feature/get current room backend

### PR DESCRIPTION
**Pull request by thabisomatau**
## Description
[Describe the purpose of this pull request]

## Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [ ] Refactor
- [ ] Other: (summarise briefly here)

## Changes Made
- implemented all the friend/following pages 
- fixed some backend logic with regards to accepting friend requests. 
- added new endpoints to get pending friend requests and potential friends
- modified userDto to include the relationship status of the user requesting the dto

## Does this break anything? (Modifying more expected behaviour/layout, etc)
- [ ] Yes
- [x] No

## Screenshots (if applicable)
image
image
image

## Performance Implications
[Discuss any potential performance implications or improvements]

## Related Issues
[Link all issues related to this PR, eg. https://github.com/COS301-SE-2024/TuneIn/...]

## Dependencies
[List any new dependencies or updates]

## Checklist
- [x] I have tested this code locally
- [x] I have reviewed the code for readability and maintainability
- [x] I have added appropriate documentation or updated existing documentation
- [x] I have ensured that my changes follow the project's coding conventions
- [x] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## Additional Notes
pages are fully implemented with the whole logic intact. however, unfollowing someone on the "followers" tab doesn't reflect on the other tabs without reflection. additions will need to be made later for improved UX
additionally, there aren't any pop-up confirmation messages. 

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

### CODE REVIEW

**Comment by lkekana** [comment]
the logic looks good but there are a couple changes needed,
- the 'friend1' and 'friend2' columns in the db are ambigious, especially if they represent a directional relationship (as the code for friend requests seems to suggest). i think it'll be better to rename the attribute, rather than document it everywhere in the code (because that would just be a bandaid solution to the bigger problem)
- there needs to be clearer distinction between `getFriendRequests` and `getPendingRequests`, just to emphasise the difference better
- `getPotentialFriends` can be renamed to `getMutualFollowers` for reusability in UserService & DtoGen and in controllers where its currently: `/users/friends/potential`
- `isFriendsOrPending()` may need a default value for `isPending` since you made the parameter optional but use it regardless of whether its given. i worry about passing type 'undefined' to the db
- i think a lot of query optimisation can happen in getPotentialFriends() using `SELECT * from follows WHERE follower = {userID} OR followee = {userID}` to get both the user's following & followers at 1 time and the loop that populates 'const potentialFriends: Prisma.users[] = [];'  adds a lot of overhead where you can do 1 query with all of the relevant users rather than 1 per user
- we also already discussed the UserDto.relationship attribute being redundant earlier in the week? it adds 4 db queries per UserDto generated. i'd be fine with keeping the attribute if you set the value using already existing info instead of the 4 extra queries

other than that, all good to me

**Comment by lkekana** [comment]
also, this branch definitely needs to go after this PR since its feature is already on develop😂

**Comment by thabisomatau** [comment]
@lkekana  just to address all of the points you have made:
 - I named the attributes that way since the friends table doesn't only show friend requests and pending requests, but also existing friendships so i thought it would be weird to name them as something like ```requester``` or ```initiator```, but i understand where it might get confusing
 - I will change the ```getPendingRequests``` to ```getSentRequests```. I think that would be sufficient enough
 - If the ```isPending``` parameter is undefined, it will just skip the field in part of the query. the reason i set it up this way is so that when the value is omitted, it just retrieves all rows in the friends table of that user regardless of whether it's pending or not
 - Noted.

**Comment by thabisomatau** [comment]
@lkekana  i forgot to tell you this earlier but i just want it to be clear that there's a difference between mutual followers and potential friend

a mutual follow merely just means both users are following one another, while a potential friend is a user you can sent a friend request to. in essence, a mutual follower can be someone who you are already friends with or someone you have sent a friend request to/recieved a friend request from. a potential friend is a subset of mutual follows. i hope this clears things up

**Review by Linda-Masia — COMMENTED** [review]
resolve the merge conflicts

**Pull request closed without merging**
