### PR TITLE
Feature search

### PR DESCRIPTION
**Pull request by NerinaBorchard**
Added the frontend for the search page with the use of filters. Added tests that work with the current frontend but will need to be changed after integrated with backend

## Type of Change
- [ ] Bug fix
- [y] New feature
- [ ] Documentation
- [ ] Refactor
- [ ] Other: (summarise briefly here)

## Changes Made
renamed test file according to other react projects

## Does this break anything? 
 No

## Screenshots (if applicable)
image

## Related Issues
https://github.com/COS301-SE-2024/TuneIn/issues/113

## Checklist
- [ ] I have tested this code locally
- [ ] I have reviewed the code for readability and maintainability
- [ ] I have added appropriate documentation or updated existing documentation
- [ ] I have ensured that my changes follow the project's coding conventions
- [ ] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## Additional Notes
[Include any additional notes or context relevant to the pull request]

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

### CODE REVIEW

**Comment by NerinaBorchard** [comment]
image
changed version

**Review by u22528492 — APPROVED** [review]

**Comment by Linda-Masia** [comment]
linting and test errors

**Comment by lkekana** [comment]
lol idk how @u22528492 approved this
as @Linda-Masia said, there are both linting & testing errors on this branch

**Comment by u22528492** [comment]
Right, my bad, didn't look at the ci/cd pipeline, just code.

**Comment by NerinaBorchard** [comment]
image
my test in terminal @lkekana @Linda-Masia 

Also the linting errors for home and index are things I never added, meaning they were there already.

**Review by lkekana — APPROVED** [review]

**Comment by lkekana** [comment]
@NerinaBorchard, one last pull from dev then i'll merge

**Pull request merged**
