### PR TITLE
merge 'feature/live-chat' into dev

### PR DESCRIPTION
**Pull request by lkekana**
- full backend implementation (tested in Postman & using the 'socket-test.js' script)
- full frontend implementation (untested, needs fixing from someone with Android Studio)

### CODE REVIEW

**Comment by lkekana** [comment]
no conflicts on first try😤

**Comment by Linda-Masia** [comment]
**MERGE CONFLICTS!**

**Comment by Linda-Masia** [comment]
**MERGE CONFLICTS!**

**Comment by lkekana** [comment]
ffs these merge conflicts came LOOOOONG after i made the PR

**Comment by lkekana** [comment]
@Linda-Masia fixed now but i believe Thabiso's still gonna be working in this branch so you can let him merge it

**Comment by Linda-Masia** [comment]
nice

**Pull request merged**
