### PR TITLE
multiple combined FEATURE and HOTFIX implementations 

### PR DESCRIPTION
**Pull request by lkekana**
## Description
Many improvements for type safety, deployment robustness and planning for the future.

## Type of Change
- [x] Bug fix
- [x] New feature
- [x] Documentation
- [x] Refactor
- [ ] Other: (summarise briefly here)

### New Functionality
- generate frontend API client for type safe API calls
- create API context for generated client for easy app-wide usage (with self-updating authentication)
- prepare & fix all backend OpenAPI documentation
- validate OpenAPI information as part of backend builds
- run unit tests, linting and building directly before backend deployment
- ensure production server runs from develop branch only & tighter deployment overall
- setup SWC compiler for backend, transpiles Typescript x20 faster (allegedly)
- add SSL so backend uses HTTPS now
- add custom logger (now unused tho)
- define all endpoints, functions & services for Jaden & Thabiso for the rest of the project
	- Room Moderation endpoints
	- User Listening stats endpoint
	- export Scheduled Room as .ics (iCal file)
	- Chat Auto Moderation service

### Fixes
- removed unused Dtos and entities
- removed Jaden's PrismaContext (there's an easier way to mock our ORM)
- ensure Jest only works with .ts files
- near complete type safety throughout backend
- fix `handleDisconnect` error
- removed most redundant code that was making up for poor type safety
- removed incorrect endpoints for exporting room queue as playlist
- fix incorrect `/users/:userID` endpoints to correctly be `/users/:username`

## Does this break anything? (Modifying more expected behaviour/layout, etc)
- [ ] Yes
- [x] No

## Performance Implications
- Better type safety
- Faster compiles
- Safer deployment
- Faster frontend integration

## Checklist
- [x] I have tested this code locally
- [x] I have reviewed the code for readability and maintainability
- [x] I have added appropriate documentation or updated existing documentation
- [x] I have ensured that my changes follow the project's coding conventions
- [x] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## Additional Notes
I'm tired.

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

### CODE REVIEW

**Comment by thabisomatau** [comment]
code coverage

**Comment by thabisomatau** [comment]
***quick question:*** why did you have to change all the api calls and endpoints in ```users/``` to make use of ```username``` instead of ```userID```?
the username attribute in the database is ***not*** a unique field and the only constraint it has is ***"not nullable"***
making use of ```username``` instead of ```userID``` will give rise to issues such as:
- There might potentially be multiple users with the same ```username```, so using this in the i.e. ```users/:username/unfollow``` might result in the incorrect user being unfollowed
- since there aren't any string format constraints in the ```username``` field, this means that if a ```username``` has special characters (i.e. spaces) then the API call url might pass in a faulty value.

Please revert changes and ensure that for all user-related endpoints, only ```userID``` is used since it's the primary key to the user table.

**Comment by lkekana** [comment]
regarding the change of some user routes to use `username` instead of `userID`,
there was a mixture of implementations & definitions in the codabase. the implementations using `userID` were incorrect and deviated from the defined schema. the fix is for consistency mostly

_why use username instead of userID?_
as previously discussed, this is in line with the convention for REST (or RESTful) APIs for which our app's routes are defined mostly in alignment with

regarding the issues that can arise from using `username` instead of `userID`,
that would be addressing the wrong problem.
- usernames have to be unique anyway (or else, what's the point lol)
- if there isn't validation on input strings, there certainly ought to be
- lastly, HTTP URLs also have a pretty well-defined structure that doesn't allow for any and all characters anyway. a bad request has multiple points at which it can fail but obviously, we should try prevent them anyway

thank you for raising these issues :)
due to your sharp eye, it might be best for you to write a hotfix to prevent these issues from happening. i'm thinking
- making `username` unique in the db
- adding string formatting & validation in both the frontend & backend

i will certainly not be reverting the change though

**Review by Linda-Masia — APPROVED** [review]
Damn Bro !!

**Pull request merged**
