### PR TITLE
Hotfix db changes

### PR DESCRIPTION
**Pull request by thabisomatau**
## Description
To fix all build issues that resulted from db changes

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Refactor
- [ ] Other: (summarise briefly here)

## Changes Made
- linting
- since the artist column in the db is changed to artists of type string[], i changed all the queries to use string array instead of just array
- i added audio_features as part of the create queries, since it's now a non-nullable field

## Does this break anything? (Modifying more expected behaviour/layout, etc)
- [ ] Yes
- [x] No

## Screenshots (if applicable)
[Include any relevant screenshots or images]

## Performance Implications
[Discuss any potential performance implications or improvements]

## Related Issues
[Link all issues related to this PR, eg. https://github.com/COS301-SE-2024/TuneIn/...]

## Dependencies
[List any new dependencies or updates]

## Checklist
- [x] I have tested this code locally
- [x] I have reviewed the code for readability and maintainability
- [x] I have added appropriate documentation or updated existing documentation
- [x] I have ensured that my changes follow the project's coding conventions
- [x] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## Additional Notes
[Include any additional notes or context relevant to the pull request]

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

### CODE REVIEW

**Comment by lkekana** [comment]
code coverage & i merge. you can leave out TasksProcessor

**Comment by thabisomatau** [comment]
@lkekana this is merely just for fixes. i'm not pushing any new feature so what do i need code coverage for?

**Comment by lkekana** [comment]
well, you're a backend developer and you did write backend code🦸🏽‍♂️

**Review by lkekana — APPROVED** [review]
beautiful 🥇

**Pull request merged**
