### PR TITLE
Feature/demo2 clean up

### PR DESCRIPTION
**Pull request by Linda-Masia**
restructured the folder structure, deleted some unused files, added device picker, and added slight improvements to a few components

### CODE REVIEW

**Comment by lkekana** [comment]
so this code has a lot of linting errors and 100+ warnings, can you fix this thoroughly in a hotfix branch after i merge your PR?

additionally, your code also reverts a bunch of changes on dev (like using StorageService instead of AsyncStorage, not using AuthManagement to handle the token, etc) that i'll fix in your branch directly

**Comment by lkekana** [comment]
okay, after making some changes & reverting some, only things left before merging is

1. re-linking the user profile from the home screen. it gives an error
2. can you fix all of the linting errors & warnings? (screenshot below)

Screenshot 2024-07-06 at 17 33 55

**Comment by Linda-Masia** [comment]
@lkekana I fixed the linting, the remaining errors are for functions that have been defined in this branch but want to use in later branches

**Comment by lkekana** [comment]
W

**Comment by lkekana** [comment]
okay, reviewing all 77 files and ~2000 lines. it looks fine, will merge soon

**Pull request merged**
