### PR TITLE
Refinement of Profile Pages

### PR DESCRIPTION
**Pull request by u22528492**
## Description
Refinement of Profile Pages

## Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Documentation
- [x] Refactor
- [ ] Other: (summarise briefly here)

## Changes Made
Changes to UX, UI, and logic

## Does this break anything? (Modifying more expected behaviour/layout, etc)
- [ ] Yes
- [x] No

## Screenshots (if applicable)
Screenshot from 2024-09-05 21-41-03
Screenshot from 2024-09-05 21-41-13
Screenshot from 2024-09-05 21-41-32
Screenshot from 2024-09-05 21-42-53

## Related Issues
https://github.com/COS301-SE-2024/TuneIn/issues/220

## Checklist
- [x] I have tested this code locally
- [ ] I have reviewed the code for readability and maintainability
- [ ] I have added appropriate documentation or updated existing documentation
- [x] I have ensured that my changes follow the project's coding conventions
- [x] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

### CODE REVIEW

**Review by lkekana — CHANGES_REQUESTED** [review]
PR looks good and the changes needed are minor. it'll probably be merged in a few hours

**DbUtilsService**
i see you brought back `buildUpdateData`, is it necessary? i had previously removed it since it was doing type checks with an `any` type that Typescript can do with native type safety
if it is needed, can you revise it to remove uses of `any` as a type

**SongInfoDto**
for optional properties, eg. songID, instead of implying it being optional by allowing for null values like:
`songID: string | null;`, 
you can use Typescript's optional designation with a `?` as,
`songID?: string;`
with this, it is either there as a string or not there at all, instead of always there but null or string. this allows for fewer null checks

additionally, for OpenAPI, you should make the decorator `@ApiPropertyOptional` instead of `@ApiProperty`

**UserDto**
you can set the type for UserDto.links to `LinksWithCount` so it's consistent with the OpenAPI info & avoids use of `any`

**UsersController**
- the convention to the `/users` paths is `:username` and not `:userID` (i had defined them incorrectly previously) so can you revise the new endpoints to match the rest
- i think the new endpoints need OpenAPI decorators like `@ApiBadRequestResponse`, etc for response codes that'll be sent if the username doesn't exist or is invalid (the decorators just acknowledges this as a possibility)

**UserService**
for `getRecentRoomDtos`, there is a `getRecentRooms` right above it, is there a specific reason not to use it with `generateMultipleRoomDto to produce the result?
i don't mind, i'm just confused

**Comment by u22528492** [comment]
Regarding the recent room getter, the one that was implemented wasn't doing it's job. I've revised it.

**Review by lkekana — CHANGES_REQUESTED** [review]
don't forget the
- [x] `?` for all optional variables in SongInfoDto (instead of `| null`) with the `@ApiPropertyOptional` & `IsOptional` decorators
- [x] can you also type the `any`'s in UserService

**Comment by thabisomatau** [comment]
@u22528492 just a quick side note. can you also ensure error handling for when a username is ***NOT*** unique? i've added some new constraints in the database so that only unique usernames are allowed.

**Review by Linda-Masia — APPROVED** [review]

**Review by lkekana — APPROVED** [review]
👍🏽

**Pull request merged**
